{% set name = "cuda-nvdisasm" %}
{% set version = "12.0.76" %}
{% set cuda_version = "12.0" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvdisasm/{{ platform }}/cuda_nvdisasm-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 0e0660100b052248529ee07353479a7d703258ef3200ac52e9676298511d10c3  # [linux64]
  sha256: aca86a9b2b7678884aa58e7a29881044e6d12dbf790b46266f08f6855a10ac79  # [ppc64le]
  sha256: 4991a102fd8d7d3aa632cf5a28df6368f4074a4ced952e7665c382c6dbdec1fd  # [aarch64]
  sha256: 7d716f14dc1342d62c9c67d4636cc1dbd496d7648b6097a53d05e1d6864a487c  # [win]

build:
  number: 0
  skip: true  # [osx]
  script:
    - cp -rv bin $PREFIX        # [linux]
    - move bin\* %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  commands:
    - test -f $PREFIX/bin/nvdisasm                    # [linux]
    - if not exist %LIBRARY_BIN%\nvdisasm.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: nvdisasm extracts information from standalone cubin files
  description: |
    nvdisasm extracts information from standalone cubin files and presents them in
    human readable format.
  doc_url: https://docs.nvidia.com/cuda/cuda-binary-utilities/

extra:
  recipe-maintainers:
    - adibbley
